name: Riggleman Research Lab
description: Computational research on polymer and glassy materials from the Riggleman Lab at the University of Pennsylvania
url: "https://mughniirfan.github.io"
baseurl: "/Lab-Website"

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - vendor
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "ghp_deploy.sh"
