name: AREIS Lab Khalifa University
description: Autonomous Robotics and Embedded Intelligent Systems Lab at Khalifa University
url: "https://mughniirfan.github.io"

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - vendor
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "ghp_deploy.sh"
